### ISSUE TITLE
p2sh

### ISSUE THREAD

**Issue by AH1111** [BTCPrivate/electrum-btcp#11]
OK, so we held some btc and are trying to import the private keys to the btcp wallet.  we get this "p2sh" ??
All other imports of private keys have worked thus far....

**Comment by Vonwelz** [comment]
I have the same issue do you receive this error:

https://ibb.co/gOd6YS

**Comment by AH1111** [comment]
Sure did

**Comment by AH1111** [comment]
I think it has something to do with multisig.....but this is not my area of
expertise....was hoping someone from the development team would chim in

**Comment by ch4ot1c** [comment]
If this is because you're coming from an old Electrum ZCL 1.0.0 2FA wallet -

- Navigate to C:/Users/YOUR-NAME/AppData/Roaming/Electrum-zcl/wallets. Open your Zclassic mutisig wallet file with Notepad (This wallet should have been setup with “From 3 co-signers” on the first slider. Select “Require 2 signatures").
- You will need to gather the 2 private keys and one public key. To find this easily, press “CTRL+F” and search for “xprv”. Copy the 2 “xprv” values as well as the last “xpub” value. You will need these in a later step.
- Create a new BTCP “Multi-signature wallet”. Select “From 3 co-signers” on the first slider. Select “Require 2 signatures” on the second slider.
To add the first co-signer, click “Use public or private keys”. Enter the first xprv key in this box.
- Add the second co-signer via a private key also.
- Add the third co-signer with the public key. Complete the set-up by adding a password if desired.
- Your BTCP should now be available in this new BTCP multisig wallet.

**Comment by AH1111** [comment]
OK, I'm no idiot but I cannot get to my xprv keys!  I can get the xpub keys.  When I open the wallet from the text file and hit control F the search and type xprv this is what I see.
![image](https://user-images.githubusercontent.com/36057398/36953102-fcdb3ce2-1fe5-11e8-808b-662bf95aa9a0.png)

**Comment by AH1111** [comment]
Problem solved, close this ticket

**Comment by Protege89** [comment]
So do we need to set an zcl-electrum multisig wallet 1st? Because I set up my zcl-electrum as standard wallet in the 1st place and still confused on how to find xprv and xpub. Please follow up. Noob question!

**Comment by AH1111** [comment]
I was making it completely harder than it was.  I used my Electrum BTC seed to restore/new wallet, standard, no 2fa or password......My BTCP showed itself .  Took 1 minute and that was it.  I assume you can do the same with the electrum ZCL seed you have........

**Comment by AH1111** [comment]
![image](https://user-images.githubusercontent.com/36057398/37059477-92d45604-215b-11e8-8512-3d34a5e7aa85.png)

**Comment by AH1111** [comment]
File>New/restore

**Comment by AH1111** [comment]
Type whatever name you want the wallet to be then hit next

![image](https://user-images.githubusercontent.com/36057398/37059565-cc0e99f2-215b-11e8-8cf3-5e2fdcbaac30.png)

**Comment by AH1111** [comment]
Next
then this 
![image](https://user-images.githubusercontent.com/36057398/37059599-dff3aac0-215b-11e8-991a-96dbb2c72b34.png)

**Comment by AH1111** [comment]
Paste your seed here, then next
![image](https://user-images.githubusercontent.com/36057398/37059660-0466696a-215c-11e8-8df1-76faf98d03b9.png)

**Comment by AH1111** [comment]
disable 2fa, don't create a password and then complete and your btcp should show up.  You will be using the seed from either the electrum BTC or ZCL wallet.  That is how easy it is.

**Comment by AH1111** [comment]
Hope this helps you

**Comment by Protege89** [comment]
got it! You're the man! Saved my life

**Comment by ch4ot1c** [comment]
<3 thank you community
