### ISSUE TITLE
File size? Why so large?

### ISSUE THREAD

**Issue by eeik** [BTCPrivate/electrum-btcp#80]
Can someone please explain why the executable is so much larger than Electrum proper and the LTC variant? Trusting this exe is difficult without fully interrogating the source given this size differential.

Any info you can share would be appreciated...

![btcp why so big](https://user-images.githubusercontent.com/5521252/40148500-844c0908-592b-11e8-991d-b6dc9f51f1cb.png)

**Comment by nolteman** [comment]
Interesting

**Comment by eeik** [comment]
Any chance you can comment on this @csulmone as it would go far to help boost trust in this wallet?

**Comment by eeik** [comment]
Closed? No comment!? Seriously? @csulmone  ... we're talking a 10x executable relative to the base wallet code you're supposedly leveraging. Surely you can provide some color on this.

**Comment by interbiznw** [comment]
Source code is there.. You can see everything... If you don't trust it, read the code and build it on your machine. It will come out the same size, then do you have any idea why it is larger?

**Comment by nolteman** [comment]
actually we are looking for a straight answer, something like, because this
and that... I am not a developer and I want an answer too.

**Comment by michaelotis** [comment]
@nolteman You probably won't get an answer like that, since it was forked from ZClassic's repo and there have been a multitude of specialized modifications for Z-based coins and then more modifications and improvements specific to Bitcoin Private but if you wanted to know, you can compare the repo with the main spesmilo repo. https://github.com/spesmilo/electrum/compare/master...BTCPrivate:master

**Comment by nolteman** [comment]
‎That's a perfect answer to understand thanks                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: michaelotisSent: Wednesday, July 11, 2018 10:53 PMTo: BTCPrivate/electrum-btcpReply To: BTCPrivate/electrum-btcpCc: nolteman; MentionSubject: Re: [BTCPrivate/electrum-btcp] File size? Why so large? (#80)@nolteman You probably won't get an answer like that, since it was forked from ZClassic's repo and there have been a multitude of specialized modifications for Z-based coins and then more modifications and improvements specific to Bitcoin Private but if you wanted to know, you can compare the repo with the main spesmilo repo. spesmilo/electrum@master...BTCPrivate:master

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BTCPrivate/electrum-btcp","title":"BTCPrivate/electrum-btcp","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/BTCPrivate/electrum-btcp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@michaelotis in #80: @nolteman You probably won't get an answer like that, since it was forked from ZClassic's repo and there have been a multitude of specialized modifications for Z-based coins and then more modifications and improvements specific to Bitcoin Private but if you wanted to know, you can compare the repo with the main spesmilo repo. https://github.com/spesmilo/electrum/compare/master...BTCPrivate:master"}],"action":{"name":"View Issue","url":"https://github.com/BTCPrivate/electrum-btcp/issues/80#issuecomment-404381154"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BTCPrivate/electrum-btcp/issues/80#issuecomment-404381154",
"url": "https://github.com/BTCPrivate/electrum-btcp/issues/80#issuecomment-404381154",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [BTCPrivate/electrum-btcp] File size? Why so large? (#80)",
"sections": [
{
"text": "",
"activityTitle": "**michaelotis**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@michaelotis",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"BTCPrivate/electrum-btcp\",\n\"issueId\": 80,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/BTCPrivate/electrum-btcp/issues/80#issuecomment-404381154"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 336113965\n}"
}
],
"themeColor": "26292E"
}
]
